# Generated by Django 6.0.3 on 2026-03-16 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAvulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento Avulso',
                'verbose_name_plural': 'Documentos Avulsos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Justificativa',
                'verbose_name_plural': 'Justificativas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, verbose_name='Número')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ofício',
                'verbose_name_plural': 'Ofícios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, verbose_name='Número')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PlanoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano de Trabalho',
                'verbose_name_plural': 'Planos de Trabalho',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Roteiro',
                'verbose_name_plural': 'Roteiros',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TermoAutorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Termo de Autorização',
                'verbose_name_plural': 'Termos de Autorização',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OficioTrecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='documentos.oficio')),
            ],
            options={
                'verbose_name': 'Trecho de Ofício',
                'verbose_name_plural': 'Trechos de Ofício',
            },
        ),
        migrations.CreateModel(
            name='RoteiroDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=255, verbose_name='Destino')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='documentos.roteiro')),
            ],
            options={
                'verbose_name': 'Destino de Roteiro',
                'verbose_name_plural': 'Destinos de Roteiro',
            },
        ),
        migrations.CreateModel(
            name='RoteiroTrecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='documentos.roteiro')),
            ],
            options={
                'verbose_name': 'Trecho de Roteiro',
                'verbose_name_plural': 'Trechos de Roteiro',
            },
        ),
    ]
