# Generated by Django 5.2.12 on 2026-03-17 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentoAvulso',
        ),
        migrations.DeleteModel(
            name='Justificativa',
        ),
        migrations.DeleteModel(
            name='OrdemServico',
        ),
        migrations.DeleteModel(
            name='PlanoTrabalho',
        ),
        migrations.DeleteModel(
            name='TermoAutorizacao',
        ),
        migrations.AlterModelOptions(
            name='oficio',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Ofício', 'verbose_name_plural': 'Ofícios'},
        ),
        migrations.AlterModelOptions(
            name='oficiotrecho',
            options={'ordering': ['oficio_id', 'ordem', 'id'], 'verbose_name': 'Trecho de ofício', 'verbose_name_plural': 'Trechos de ofício'},
        ),
        migrations.AlterModelOptions(
            name='roteiro',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': 'Roteiro', 'verbose_name_plural': 'Roteiros'},
        ),
        migrations.AlterModelOptions(
            name='roteirodestino',
            options={'ordering': ['roteiro_id', 'ordem', 'id'], 'verbose_name': 'Destino de roteiro', 'verbose_name_plural': 'Destinos de roteiro'},
        ),
        migrations.AlterModelOptions(
            name='roteirotrecho',
            options={'ordering': ['roteiro_id', 'ordem', 'id'], 'verbose_name': 'Trecho de roteiro', 'verbose_name_plural': 'Trechos de roteiro'},
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='oficiotrecho',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='roteiro',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='roteiro',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='roteirodestino',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='roteirotrecho',
            name='descricao',
        ),
        migrations.AddField(
            model_name='oficio',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='cidade_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_sede_cidade', to='cadastros.cidade', verbose_name='Cidade da sede'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='combustivel',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Combustível'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='custeio_tipo',
            field=models.CharField(choices=[('ORGAO', 'Órgão'), ('OUTRA_INSTITUICAO', 'Outra instituição')], default='ORGAO', max_length=30, verbose_name='Tipo de custeio'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='data_criacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='estado_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_sede_estado', to='cadastros.estado', verbose_name='Estado da sede'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='gerar_termo_preenchido',
            field=models.BooleanField(default=False, verbose_name='Gerar termo preenchido'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='justificativa_texto',
            field=models.TextField(blank=True, default='', verbose_name='Justificativa'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motivo',
            field=models.TextField(blank=True, default='', verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Motorista'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_carona',
            field=models.BooleanField(default=False, verbose_name='Motorista em carona'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_oficio',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Ofício do motorista'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_oficio_ano',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano do ofício do motorista'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_oficio_numero',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número do ofício do motorista'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_protocolo',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Protocolo do motorista'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='nome_instituicao_custeio',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome da instituição de custeio'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='placa',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Placa'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='porte_transporte_armas',
            field=models.BooleanField(default=True, verbose_name='Porte/transporte de armas'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='protocolo',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Protocolo'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='quantidade_diarias',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Quantidade de diárias'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_chegada_cidade',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Cidade de chegada do retorno'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_chegada_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data de chegada do retorno'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_chegada_hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de chegada do retorno'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distância do retorno (km)'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_duracao_estimada_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração estimada do retorno (min)'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_rota_calculada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Retorno calculado em'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_rota_fonte',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Fonte da rota de retorno'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_saida_cidade',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Cidade de saída do retorno'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_saida_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data de saída do retorno'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_saida_hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de saída do retorno'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_tempo_adicional_min',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo adicional do retorno (min)'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_tempo_cru_estimado_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo cru estimado do retorno (min)'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='roteiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to='documentos.roteiro', verbose_name='Roteiro'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='tipo_destino',
            field=models.CharField(choices=[('ESTADUAL', 'Estadual'), ('INTERESTADUAL', 'Interestadual')], default='ESTADUAL', max_length=20, verbose_name='Tipo de destino'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='tipo_viatura',
            field=models.CharField(choices=[('PROPRIA', 'Própria'), ('LOCADA', 'Locada'), ('OUTRA', 'Outra')], default='PROPRIA', max_length=20, verbose_name='Tipo de viatura'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='valor_diarias',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Valor de diárias'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='valor_diarias_extenso',
            field=models.TextField(blank=True, default='', verbose_name='Valor de diárias por extenso'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to='cadastros.veiculo', verbose_name='Veículo'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='viajantes',
            field=models.ManyToManyField(blank=True, related_name='oficios', to='cadastros.viajante', verbose_name='Viajantes'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='chegada_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data de chegada'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='chegada_hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de chegada'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='destino_cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trechos_oficio_destino_cidade', to='cadastros.cidade', verbose_name='Cidade de destino'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='destino_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trechos_oficio_destino_estado', to='cadastros.estado', verbose_name='Estado de destino'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distância (km)'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='duracao_estimada_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração estimada (min)'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='origem_cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trechos_oficio_origem_cidade', to='cadastros.cidade', verbose_name='Cidade de origem'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='origem_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trechos_oficio_origem_estado', to='cadastros.estado', verbose_name='Estado de origem'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='rota_calculada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rota calculada em'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='rota_fonte',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Fonte da rota'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='saida_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data de saída'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='saida_hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de saída'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='tempo_adicional_min',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo adicional (min)'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='tempo_cru_estimado_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo cru estimado (min)'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='chegada_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Chegada'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='duracao_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (min)'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='origem_cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roteiros_origem_cidade', to='cadastros.cidade', verbose_name='Cidade de origem'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='origem_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roteiros_origem_estado', to='cadastros.estado', verbose_name='Estado de origem'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='retorno_chegada_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Chegada de retorno'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='retorno_duracao_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração de retorno (min)'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='retorno_saida_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Saída de retorno'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='saida_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Saída'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='roteirodestino',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roteiro_destinos', to='cadastros.cidade', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='roteirodestino',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='roteirodestino',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roteiro_destinos', to='cadastros.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='roteirodestino',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='roteirodestino',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='chegada_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Chegada'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='destino_cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trechos_roteiro_destino_cidade', to='cadastros.cidade', verbose_name='Cidade de destino'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='destino_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trechos_roteiro_destino_estado', to='cadastros.estado', verbose_name='Estado de destino'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distância (km)'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='duracao_estimada_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração estimada (min)'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='origem_cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trechos_roteiro_origem_cidade', to='cadastros.cidade', verbose_name='Cidade de origem'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='origem_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trechos_roteiro_origem_estado', to='cadastros.estado', verbose_name='Estado de origem'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='rota_calculada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rota calculada em'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='rota_fonte',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Fonte da rota'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='saida_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Saída'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='tempo_adicional_min',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo adicional (min)'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='tempo_cru_estimado_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo cru estimado (min)'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='tipo',
            field=models.CharField(choices=[('IDA', 'Ida'), ('RETORNO', 'Retorno')], default='IDA', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='oficiotrecho',
            name='oficio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='documentos.oficio', verbose_name='Ofício'),
        ),
        migrations.AlterField(
            model_name='roteiro',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='roteirodestino',
            name='roteiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='documentos.roteiro', verbose_name='Roteiro'),
        ),
        migrations.AlterField(
            model_name='roteirotrecho',
            name='roteiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='documentos.roteiro', verbose_name='Roteiro'),
        ),
        migrations.AddConstraint(
            model_name='oficio',
            constraint=models.UniqueConstraint(fields=('numero', 'ano'), name='unique_oficio_numero_ano'),
        ),
        migrations.AddConstraint(
            model_name='oficiotrecho',
            constraint=models.UniqueConstraint(fields=('oficio', 'ordem'), name='unique_oficio_trecho_ordem'),
        ),
    ]
